### ISSUE TITLE
Server-side BepInEx Set-up

### ISSUE THREAD

**Issue by rdev34** [Paradigm-MP/Luaxe#1]
Installing bepinex server-side: https://youtu.be/gOGYQRHpp2c

We also need to figure out how to separate the client and server code both organizationally in the codebase and with the built Luaxe.dll.

We could do separate projects in the solution for client and server.
Then i would think we would have more control over the build process for each project

blocks: #2

**Comment by rdev34** [comment]
https://github.com/RandyKnapp/ValheimMods/blob/72410972d684754513025d3268250868bbd5ce07/EpicLoot/Adventure/BountyTarget.cs#L55

**Comment by benank** [comment]
Done
