### ISSUE TITLE
Client <-> Server Communication 'Network' class

### ISSUE THREAD

**Issue by rdev34** [Paradigm-MP/Luaxe#2]
We need to build up a Network class to abstract the client-server communication in Valheim
example/research of client-server communication:

https://github.com/RandyKnapp/ValheimMods/blob/72410972d684754513025d3268250868bbd5ce07/EpicLoot/Adventure/BountyTarget.cs#L55

https://github.com/HackShardGaming/World-of-Valheim-Public/blob/56905abd6dd49092c2f75247a1564920bb5da5af/WorldofValheimServerSideCharacters/RPC/RPC.cs

https://github.com/aequasi/valheim-discord-notifier/blob/6b05835cc6e7534e41145feb3ee32360aa54c0d2/Patches/PlayerPatch.cs

**Comment by benank** [comment]
Done
